version: '3.1'

services:

  db:
    image: postgres:12.1
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: user_db
    ports:
    - '5432:5432'
    volumes: 
    - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql